version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: process_flow_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://root:postgres@db:5432/process_flow_db
      JWT_SECRET: your-production-secret-key
      CLIENT_URL: http://localhost:8080
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: