services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: process_flow_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://root:postgres@db:5432/process_flow_db
      JWT_SECRET: your-production-secret-key
      CLIENT_URL: http://localhost:8080
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./uploads:/app/uploads

  client:
    build: ./client
    ports:
      - "8080:8080"
    environment:
      VUE_APP_API_URL: http://localhost:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - app

volumes:
  postgres_data: